# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150609085908) do

  create_table "apps", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.text     "html"
    t.string   "position"
    t.text     "js"
    t.integer  "connection_id"
    t.string   "object"
    t.string   "cssid"
    t.string   "citation"
  end

  add_index "apps", ["connection_id"], name: "index_apps_on_connection_id"

  create_table "articles", force: true do |t|
    t.string   "title"
    t.string   "date"
    t.text     "body"
    t.string   "imagePath"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
  end

  create_table "assignments", force: true do |t|
    t.integer  "app_id"
    t.integer  "article_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "assignments", ["app_id"], name: "index_assignments_on_app_id"
  add_index "assignments", ["article_id"], name: "index_assignments_on_article_id"

  create_table "connections", force: true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "players", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.string   "height"
    t.integer  "weight"
    t.string   "handedness"
    t.string   "image"
    t.string   "league"
    t.string   "type"
    t.decimal  "adv_fg_perc"
    t.decimal  "adv_minutes_pg"
    t.decimal  "and1_pg"
    t.decimal  "ast_pg"
    t.decimal  "badpass_to_pg"
    t.decimal  "blk_pg"
    t.decimal  "blocking_fouls_committed_pg"
    t.decimal  "C_position_percminutes"
    t.decimal  "corner_perc"
    t.decimal  "corner_perc3pt"
    t.decimal  "dist_0to3feet_perc"
    t.decimal  "dist_0to3feet_percshots"
    t.decimal  "dist_10to16feet_perc"
    t.decimal  "dist_10to16feet_percshots"
    t.decimal  "dist_16to3pt_perc"
    t.decimal  "dist_16to3pt_percshots"
    t.decimal  "dist_3to10feet_perc"
    t.decimal  "dist_3to10feet_percshots"
    t.decimal  "distance_avg"
    t.decimal  "drb_pg"
    t.decimal  "dunks_made_pg"
    t.decimal  "dunks_percshots"
    t.decimal  "efg_perc"
    t.decimal  "fg_perc"
    t.decimal  "fga_pg"
    t.decimal  "fgm_pg"
    t.decimal  "fouls_pg"
    t.decimal  "ft_perc"
    t.decimal  "fta_pg"
    t.decimal  "ftm_pg"
    t.decimal  "heaves_attempted_pg"
    t.decimal  "heaves_made_pg"
    t.decimal  "intentional_fouls_committed_pg"
    t.decimal  "lostball_to_pg"
    t.decimal  "minutes_pg"
    t.decimal  "offensive_fouls_committed_pg"
    t.decimal  "orb_pg"
    t.decimal  "other_to_pg"
    t.decimal  "PF_position_percminutes"
    t.decimal  "PG_position_percminutes"
    t.decimal  "plusminus_oncourt_per100"
    t.decimal  "plusminus_onvsoffcourt_per100"
    t.decimal  "pts_generated_by_ast_pg"
    t.decimal  "pts_pg"
    t.decimal  "SF_position_percminutes"
    t.decimal  "SG_position_percminutes"
    t.decimal  "shooting_fouls_committed_pg"
    t.decimal  "shooting_fouls_drawn_pg"
    t.decimal  "shots_blocked_pg"
    t.decimal  "stl_pg"
    t.decimal  "threept_fga_pg"
    t.decimal  "threept_fgm_pg"
    t.decimal  "threept_perc"
    t.decimal  "threept_percasstd"
    t.decimal  "threept_percshots"
    t.decimal  "to_pg"
    t.decimal  "trb_pg"
    t.decimal  "twopt_fga_pg"
    t.decimal  "twopt_fgm_pg"
    t.decimal  "twopt_perc"
    t.decimal  "twopt_perc_shots"
    t.decimal  "twopt_percasstd"
    t.integer  "adv_games"
    t.integer  "games"
    t.integer  "games_started"
  end

  create_table "seasonassociations", force: true do |t|
    t.integer "player_id"
    t.integer "season_id"
  end

  add_index "seasonassociations", ["player_id"], name: "index_seasonassociations_on_player_id"
  add_index "seasonassociations", ["season_id"], name: "index_seasonassociations_on_season_id"

  create_table "seasons", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.string   "season"
    t.integer  "age"
    t.string   "team"
    t.string   "league"
    t.string   "position"
    t.string   "type"
    t.decimal  "and1_pg"
    t.decimal  "ast_pg"
    t.decimal  "badpass_to_pg"
    t.decimal  "blk_pg"
    t.decimal  "blocking_fouls_committed_pg"
    t.decimal  "C_position_percminutes"
    t.decimal  "corner_perc"
    t.decimal  "corner_perc3pt"
    t.decimal  "dist_0to3feet_perc"
    t.decimal  "dist_0to3feet_percshots"
    t.decimal  "dist_10to16feet_perc"
    t.decimal  "dist_10to16feet_percshots"
    t.decimal  "dist_16to3pt_perc"
    t.decimal  "dist_16to3pt_percshots"
    t.decimal  "dist_3to10feet_perc"
    t.decimal  "dist_3to10feet_percshots"
    t.decimal  "distance_avg"
    t.decimal  "drb_pg"
    t.decimal  "dunks_made_pg"
    t.decimal  "dunks_percshots"
    t.decimal  "efg_perc"
    t.decimal  "fg_perc"
    t.decimal  "fga_pg"
    t.decimal  "fgm_pg"
    t.decimal  "fouls_pg"
    t.decimal  "ft_perc"
    t.decimal  "fta_pg"
    t.decimal  "ftm_pg"
    t.decimal  "heaves_attempted_pg"
    t.decimal  "heaves_made_pg"
    t.decimal  "intentional_fouls_committed_pg"
    t.decimal  "lostball_to_pg"
    t.decimal  "minutes_pg"
    t.decimal  "offensive_fouls_committed_pg"
    t.decimal  "orb_pg"
    t.decimal  "other_to_pg"
    t.decimal  "PF_position_percminutes"
    t.decimal  "PG_position_percminutes"
    t.decimal  "plusminus_oncourt_per100"
    t.decimal  "plusminus_onvsoffcourt_per100"
    t.decimal  "pts_generated_by_ast_pg"
    t.decimal  "pts_pg"
    t.decimal  "SF_position_percminutes"
    t.decimal  "SG_position_percminutes"
    t.decimal  "shooting_fouls_committed_pg"
    t.decimal  "shooting_fouls_drawn_pg"
    t.decimal  "shots_blocked_pg"
    t.decimal  "stl_pg"
    t.decimal  "threept_fga_pg"
    t.decimal  "threept_fgm_pg"
    t.decimal  "threept_perc"
    t.decimal  "threept_percasstd"
    t.decimal  "threept_percshots"
    t.decimal  "to_pg"
    t.decimal  "trb_pg"
    t.decimal  "twopt_fga_pg"
    t.decimal  "twopt_fgm_pg"
    t.decimal  "twopt_perc"
    t.decimal  "twopt_perc_shots"
    t.decimal  "twopt_percasstd"
    t.integer  "games"
    t.integer  "games_started"
  end

end
